<?php return array(
    'root' => array(
        'name' => 'ithemes/ithemes-security-pro',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => 'a65e085a2b31f25a7700dc68f39c4c2573ea0463',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'ithemes/ithemes-security-pro' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'a65e085a2b31f25a7700dc68f39c4c2573ea0463',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pimple/pimple' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'a94b3a4db7fb774b3d78dad2315ddc07629e1bed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pimple/pimple',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '2ae37329ee82f91efadc282cc2d527fd6065a5ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
